# Generated by Django 3.2.15 on 2022-08-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=256, verbose_name='Полное имя')),
                ('user_phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('user_email', models.CharField(max_length=256, verbose_name='E-mail')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('checked', models.BooleanField(help_text='Поставить отметку, если тема закрыта', verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Сообщение/Вопрос',
                'verbose_name_plural': 'Сообщения/Вопросы',
                'ordering': ['-date_sent', 'fullname'],
            },
        ),
    ]
